name: Run CI Operations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: amrswe/cpp-utils
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

