name: Run CI Operations

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: amrswe/cpp-utils
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Give execute permission to scripts
        run: chmod +x ./scripts/*.sh

      - name: Check files/folders naming conventions
        run: ./scripts/naming_convention_check.sh

      - name: Check code formatting
        run: ./scripts/code_formatting_check.sh

      - name: Static analysis with cppcheck
        run: cppcheck --enable=all --inconclusive --check-config --xml --xml-version=2 --suppress=missingIncludeSystem . 2> cppcheck.xml

      - name: Upload cppcheck.xml
        uses: actions/upload-artifact@v4
        with:
          name: cppcheck
          path: cppcheck.xml

      - name: Run unit tests
        run: make test

      - name: Run memory leak checks
        run: make check_memory_leaks

